# Exported from Render on 2025-10-27T19:09:27Z
version: "1"
services:
- type: web
  name: nawah-dashboard-events
  runtime: node
  repo: https://github.com/nawahtkui/nawah-dashboard-events
  plan: free
  envVars:
  - key: API_TOKEN
    sync: false
  - key: PRIVATE_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: PORT
    sync: false
  - key: NODE_VERSION
    sync: false
  region: oregon
  buildCommand: npm install
  startCommand: npm start
  autoDeployTrigger: commit
